package View;
import Controller.ControllerRental;
import Model.ModelRental;
import java.awt.Color;
import javax.swing.JTable;

public class ViewPeminjam extends javax.swing.JFrame {
    public Object Kolom[]={"Nama", "NIK", "Alamat", "No. HP"};
    
    public ViewPeminjam() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.getContentPane().setBackground(Color.white);
        new ControllerRental(new ModelRental(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        bTrx = new javax.swing.JButton();
        bRental = new javax.swing.JButton();
        juduldata = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        labelbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(835, 550));
        setPreferredSize(new java.awt.Dimension(837, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(50, 22, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 6));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo.png"))); // NOI18N
        logo.setToolTipText("");
        logo.setPreferredSize(new java.awt.Dimension(250, 225));

        bTrx.setBackground(new java.awt.Color(50, 22, 0));
        bTrx.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        bTrx.setForeground(new java.awt.Color(255, 255, 255));
        bTrx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/add.png"))); // NOI18N
        bTrx.setText("TAMBAH TRANSAKSI");
        bTrx.setBorder(null);
        bTrx.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bTrx.setName(""); // NOI18N
        bTrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTrxActionPerformed(evt);
            }
        });

        bRental.setBackground(new java.awt.Color(50, 22, 0));
        bRental.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        bRental.setForeground(new java.awt.Color(255, 255, 255));
        bRental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/list.png"))); // NOI18N
        bRental.setText("DAFTAR RENTAL");
        bRental.setBorder(null);
        bRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRentalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bRental, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(bTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(bRental, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 510));

        juduldata.setBackground(new java.awt.Color(204, 255, 204));
        juduldata.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        juduldata.setForeground(new java.awt.Color(255, 255, 204));
        juduldata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        juduldata.setText("DATA PEMINJAM");
        juduldata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 5));
        getContentPane().add(juduldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, -1, 510, 110));

        tabel.setBackground(new java.awt.Color(51, 51, 0));
        tabel.setFont(new java.awt.Font("Perpetua", 0, 16)); // NOI18N
        tabel.setForeground(new java.awt.Color(255, 255, 255));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "NIK", "Alamat", "No. Hp"
            }
        ));
        tabel.setGridColor(new java.awt.Color(102, 102, 0));
        tabel.setSelectionBackground(new java.awt.Color(255, 153, 0));
        tabel.setSelectionForeground(new java.awt.Color(102, 102, 0));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 500, 400));

        labelbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bg.jpg"))); // NOI18N
        getContentPane().add(labelbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 820, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTrxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTrxActionPerformed
        new ViewInput().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bTrxActionPerformed

    private void bRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRentalActionPerformed
        new ViewRental().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRentalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPeminjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPeminjam().setVisible(true);
            }
        });
    }

    public JTable getTabel() {
        return tabel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRental;
    private javax.swing.JButton bTrx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel juduldata;
    private javax.swing.JLabel labelbg;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
